import Head from 'next/head';
import '../styles/globals.css';

function MyApp({ Component, pageProps }) {
  return (
    <>
      {}
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="Generated by Next.js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {}
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
